const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const defaults=[{id:crypto.randomUUID(),name:"모카",description:"anthropomorphic black cat detective, amber eyes, beige trench coat, dark fedora"},{id:crypto.randomUUID(),name:"루나",description:"small glowing moon spirit, silver hair, star-shaped pupils, floating white dress"}];
const state={pages:[],layouts:[],page:0,selected:null,characters:defaults,readOrder:"rtl",history:[],queueStop:false,apiKey:sessionStorage.getItem("toonitKey")||"",model:localStorage.getItem("toonitModel")||"gemini-2.5-flash"};
const layoutSets={2:[[[1,1,13,7],[1,7,13,13]],[[1,1,8,13],[8,1,13,13]]],3:[[[1,1,13,7],[1,7,7,13],[7,7,13,13]],[[1,1,8,13],[8,1,13,6],[8,6,13,13]],[[1,1,7,6],[7,1,13,6],[1,6,13,13]]],4:[[[1,1,13,7],[1,7,6,13],[6,7,10,13],[10,7,13,13]],[[1,1,7,8],[7,1,13,5],[7,5,13,8],[1,8,13,13]],[[1,1,5,13],[5,1,13,6],[5,6,9,13],[9,6,13,13]]],5:[[[1,1,9,7],[9,1,13,7],[1,7,5,13],[5,7,9,13],[9,7,13,13]],[[1,1,7,5],[7,1,13,5],[1,5,9,10],[9,5,13,10],[1,10,13,13]]],6:[[[1,1,9,7],[9,1,13,4],[9,4,13,7],[1,7,5,13],[5,7,9,13],[9,7,13,13]],[[1,1,5,7],[5,1,9,7],[9,1,13,7],[1,7,7,10],[7,7,13,10],[1,10,13,13]]],7:[[[1,1,9,6],[9,1,13,4],[9,4,13,6],[1,6,5,10],[5,6,9,10],[9,6,13,10],[1,10,13,13]]],8:[[[1,1,7,5],[7,1,13,5],[1,5,5,9],[5,5,9,9],[9,5,13,9],[1,9,5,13],[5,9,9,13],[9,9,13,13]]]};
const beats=[["도시의 밤","와이드 샷","네온 불빛이 물웅덩이에 번지는 비 오는 밤거리. 모카가 우산을 쓰고 걷는다.","오늘도 별일 없는 하루군.","모카"],["수상한 편지","익스트림 클로즈업","모카가 초승달 봉인이 찍힌 은빛 편지를 발견한다.","이건 누구 편지지?","모카"],["달의 의뢰","미디엄 샷","편지를 펼치자 작은 달의 지도가 푸른 빛과 함께 공중에 떠오른다.","사라진 달을 찾아주세요.","모카,루나"],["탐정의 결심","로우 앵글","모카가 코트를 여미고 달이 사라진 밤하늘을 올려다본다.","좋아. 사건을 시작하지.","모카"],["옥상의 흔적","오버숄더 샷","젖은 옥상 난간 위에 반짝이는 달빛 가루가 이어져 있다.","흔적은 아직 따뜻해.","모카"],["그림자의 습격","더치 앵글","거대한 그림자가 옥상을 덮고 모카를 향해 손을 뻗는다.","쉽게 끝나진 않겠군!","모카"],["지하의 달","익스트림 와이드 샷","도시 아래 거대한 지하 호수에 달과 루나가 갇혀 있다.","드디어 찾았어.","모카,루나"],["달빛의 귀환","실루엣 와이드 샷","달이 도시 위로 돌아오고 모카와 루나가 옥상에 나란히 선다.","다음 사건도 부탁할게.","모카,루나"]];
const chunk=(a,n)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
function log(t){let d=document.createElement("div");d.className="log-msg";d.textContent=t;$("#messageLog").prepend(d)}
function saved(){clearTimeout(saved.t);$("#saveState").textContent="저장 중…";saved.t=setTimeout(()=>{$("#saveState").textContent="자동 저장됨";localStorage.setItem("toonitProject",JSON.stringify({pages:state.pages,layouts:state.layouts,characters:state.characters,title:$("#projectTitle").value,prompt:$("#mangaPrompt").value,base:$("#basePrompt").value,negative:$("#negativePrompt").value,readOrder:state.readOrder}))},350)}
function load(){try{let d=JSON.parse(localStorage.getItem("toonitProject"));if(!d)return;state.pages=d.pages||[];state.layouts=d.layouts||[];state.characters=d.characters||defaults;state.readOrder=d.readOrder||"rtl";$("#projectTitle").value=d.title||"새 프로젝트";$("#mangaPrompt").value=d.prompt||"";$("#basePrompt").value=d.base||$("#basePrompt").value;$("#negativePrompt").value=d.negative||$("#negativePrompt").value}catch{}}
function count(){$("#promptCount").textContent=`${$("#mangaPrompt").value.length}자`}
$$(".tabs button").forEach(b=>b.onclick=()=>{$$(".tabs button").forEach(x=>x.classList.toggle("active",x===b));$$(".tab-panel").forEach(x=>x.classList.remove("active"));$(`#${b.dataset.tab}Tab`).classList.add("active")});
$$(".view").forEach(b=>b.onclick=()=>{$$(".view").forEach(x=>x.classList.toggle("active",x===b));setView(b.dataset.view)});
["projectTitle","mangaPrompt","basePrompt","negativePrompt"].forEach(id=>$(`#${id}`).oninput=()=>{count();saved()});
$("#readOrder").onclick=e=>{if(!e.target.dataset.value)return;state.readOrder=e.target.dataset.value;$$("#readOrder button").forEach(b=>b.classList.toggle("active",b===e.target));render()};
function renderCharacters(){let l=$("#characterList");l.innerHTML="";state.characters.forEach(c=>{let n=$("#characterTemplate").content.cloneNode(true);$(".avatar",n).textContent=c.name[0]||"?";$(".char-name",n).value=c.name;$(".char-desc",n).value=c.description;$(".char-name",n).oninput=e=>{c.name=e.target.value;saved()};$(".char-desc",n).oninput=e=>{c.description=e.target.value;saved()};$(".remove-char",n).onclick=()=>{state.characters=state.characters.filter(x=>x.id!==c.id);renderCharacters();renderInspector()};l.append(n)})}
$("#addCharacter").onclick=()=>{state.characters.push({id:crypto.randomUUID(),name:`캐릭터 ${state.characters.length+1}`,description:"appearance, outfit, personality"});renderCharacters()};
function makePanel(b){let names=b[4].split(",").filter(n=>state.characters.some(c=>c.name===n)),profiles=state.characters.filter(c=>names.includes(c.name)).map(c=>`${c.name}: ${c.description}`).join("; ");return{id:crypto.randomUUID(),title:b[0],shot:b[1],description:b[2],dialogue:b[3],characters:names,imagePrompt:`${$("#basePrompt").value}, ${b[1]}, ${b[2]}, ${profiles}, no text`,status:"ready",reference:""}}
const clamp=(n,min,max)=>{let value=Number(n);return Math.min(max,Math.max(min,Number.isFinite(value)?Math.round(value):min))};
function presetLayout(count,pageIndex,variant=0){let set=layoutSets[count]||layoutSets[8],rects=set[variant%set.length];return rects.map((r,i)=>({x:r[0],y:r[1],w:r[2]-r[0],h:r[3]-r[1],rotation:(pageIndex+i)%5===3?(i%2?4:-4):0,z:i+1}))}
function normalizeLayout(layout,fallback={}){let x=clamp(layout?.x??fallback.x,1,11),y=clamp(layout?.y??fallback.y,1,11),w=clamp(layout?.w??fallback.w,2,13-x),h=clamp(layout?.h??fallback.h,2,13-y);return{x,y,w,h,rotation:clamp(layout?.rotation??fallback.rotation??0,-7,7),z:clamp(layout?.z??fallback.z??1,1,20)}}
function normalizePages(raw){let source=Array.isArray(raw?.pages)?raw.pages:Array.isArray(raw?.panels)?chunk(raw.panels,Math.max(2,+$("#panelRange").value)):[];return source.map((page,pi)=>{let panels=Array.isArray(page)?page:page.panels||[],fallback=presetLayout(panels.length,pi);return panels.slice(0,8).map((x,i)=>({...x,id:x.id||crypto.randomUUID(),status:x.status||"ready",reference:x.reference||"",characters:Array.isArray(x.characters)?x.characters:[],imagePrompt:x.imagePrompt?.startsWith($("#basePrompt").value)?x.imagePrompt:`${$("#basePrompt").value}, ${x.imagePrompt||""}`,layout:normalizeLayout(x.layout,fallback[i])}))}).filter(x=>x.length)}
function demo(){let per=Math.max(2,+$("#panelRange").value),total=Math.max(1,+$("#pages").value)*per,pages=chunk(Array.from({length:total},(_,i)=>makePanel(beats[i%beats.length])),per);return pages.map((page,pi)=>page.map((p,i)=>({...p,layout:presetLayout(page.length,pi)[i]})))}
async function askGemini(prompt,temperature){let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(state.model)}:generateContent?key=${encodeURIComponent(state.apiKey)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json",temperature}})});if(!r.ok)throw Error(`Gemini ${r.status}`);let d=await r.json();return JSON.parse(d.candidates[0].content.parts[0].text)}
async function gemini(deep){let pageCount=Math.max(1,+$("#pages").value),per=Math.max(2,+$("#panelRange").value),prompt=`You are a professional manga director and page designer. Turn the story into exactly ${pageCount} pages with about ${per} panels per page (2-8 allowed when pacing benefits). Design the panel composition yourself; do not use a repetitive grid. Use a 12x12 page coordinate system. For every panel, layout x/y are start lines from 1 to 11, w/h keep the panel inside line 13, rotation is -7 to 7 degrees, and z is 1-20. Occasionally use a visibly tilted panel for action, shock, instability, or emphasis, but keep most panels straight and readable. Avoid harmful overlap; reserve breathing room and create varied panel sizes. ${deep?"Deep mode: prioritize visual continuity, dramatic page turns, bold composition, varied camera angles, and detailed prompts.":"Keep the storyboard concise and layouts readable."} Reading direction: ${state.readOrder}. Known characters: ${JSON.stringify(state.characters)}. Korean story: ${$("#mangaPrompt").value}. Return JSON only: {"pages":[{"panels":[{"title":"Korean","shot":"Korean camera","description":"Korean visual scene","dialogue":"Korean","characters":["known name"],"imagePrompt":"English","layout":{"x":1,"y":1,"w":6,"h":5,"rotation":0,"z":1}}]}]}`;let pages=normalizePages(await askGemini(prompt,deep?.9:.55));if(!pages.length)throw Error("Gemini가 유효한 페이지 구성을 반환하지 않았습니다");return pages}
async function analyze(deep){let b=deep?$("#geminiDeep"):$("#geminiLite");b.disabled=true;b.textContent="분석 중…";log(`${deep?"Deep":"Lite"} 분석을 시작했습니다.`);try{state.pages=state.apiKey?await gemini(deep):demo();log(`${state.apiKey?"Gemini":"데모 엔진"}가 ${state.pages.flat().length}개 컷을 구성했습니다.`)}catch(e){state.pages=demo();log(`${e.message}: 데모 구성으로 전환했습니다.`)}state.layouts=state.pages.map((_,i)=>i%3);state.page=0;state.selected=state.pages[0][0].id;history(deep?"Gemini Deep":"Gemini Lite");render();setView("editor");b.disabled=false;b.textContent=deep?"✦ Gemini Deep":"Gemini Lite"}
$("#geminiLite").onclick=()=>analyze(false);$("#geminiDeep").onclick=()=>analyze(true);
function layoutFor(count,pageIndex){let set=layoutSets[count]||layoutSets[8];return set[(state.layouts[pageIndex]||0)%set.length]}
function node(p,i,total,pageIndex){let n=$("#panelTemplate").content.cloneNode(true),a=$(".panel",n),rect=layoutFor(total,pageIndex)[i],fallback=rect&&{x:rect[0],y:rect[1],w:rect[2]-rect[0],h:rect[3]-rect[1],z:i+1},layout=p.layout||normalizeLayout(null,fallback);if(layout){a.style.gridColumn=`${layout.x} / span ${layout.w}`;a.style.gridRow=`${layout.y} / span ${layout.h}`;a.style.transform=`rotate(${layout.rotation||0}deg)`;a.style.zIndex=layout.z||i+1}a.classList.toggle("selected",p.id===state.selected);$(".panel-index",n).textContent=String(i+1).padStart(2,"0");$(".panel-name",n).textContent=p.title;$(".panel-camera",n).textContent=p.shot;$(".speech",n).textContent=p.dialogue;$(".panel-state",n).textContent=p.status.toUpperCase();if(p.status==="generated")$(".panel-image",n).classList.add("generated");if(p.reference){$(".panel-image",n).style.cssText=`background-image:url(${p.reference});background-size:cover`;$(".placeholder",n).style.display="none"}a.onclick=()=>{state.selected=p.id;render()};return n}
function render(){let has=!!state.pages.length,page=state.pages[state.page]||[],c=$("#mangaPage");$("#emptyState").classList.toggle("hidden",has);$("#canvasWrap").classList.toggle("hidden",!has);$("#pageLabel").textContent=`Page ${has?state.page+1:0} / ${state.pages.length}`;c.innerHTML="";c.style.direction=state.readOrder;c.className=`manga-page count-${page.length}`;page.forEach((p,i)=>c.append(node(p,i,page.length,state.page)));renderInspector();renderPreview();renderHistory();saved()}
function selected(){return state.pages.flat().find(p=>p.id===state.selected)}
function renderInspector(){let p=selected();$("#inspectorEmpty").classList.toggle("hidden",!!p);$("#inspector").classList.toggle("hidden",!p);if(!p)return;$("#panelBadge").textContent=`PANEL ${String(state.pages.flat().indexOf(p)+1).padStart(2,"0")}`;["Title","Shot","Description","Dialogue","ImagePrompt"].forEach(k=>$(`#panel${k}`).value=p[k[0].toLowerCase()+k.slice(1)]);let x=$("#panelCharacters");x.innerHTML="";state.characters.forEach(c=>{let l=document.createElement("label");l.innerHTML=`<input type="checkbox" value="${c.id}" ${p.characters.includes(c.name)?"checked":""}> ${c.name}`;x.append(l)});let box=$(".reference-box");box.classList.toggle("has-image",!!p.reference);box.style.backgroundImage=p.reference?`url(${p.reference})`:""}
$("#savePanel").onclick=()=>{let p=selected();if(!p)return;["Title","Shot","Description","Dialogue","ImagePrompt"].forEach(k=>p[k[0].toLowerCase()+k.slice(1)]=$(`#panel${k}`).value);p.characters=$$("#panelCharacters input:checked").map(x=>state.characters.find(c=>c.id===x.value)?.name).filter(Boolean);log(`「${p.title}」 컷을 수정했습니다.`);render()};
$("#deletePanel").onclick=()=>{state.pages=state.pages.map(pg=>pg.filter(p=>p.id!==state.selected)).filter(pg=>pg.length);state.page=Math.max(0,Math.min(state.page,state.pages.length-1));state.selected=null;history("패널 삭제");render()};
$("#referenceFile").onchange=e=>{let f=e.target.files[0],p=selected();if(!f||!p)return;let r=new FileReader();r.onload=()=>{p.reference=r.result;p.status="generated";render()};r.readAsDataURL(f)};
function renderPreview(){let w=$("#previewWrap");w.innerHTML="";state.pages.forEach((pg,pi)=>{let d=document.createElement("div");d.className="preview-page";d.style.direction=state.readOrder;pg.forEach((p,i)=>d.append(node(p,i,pg.length,pi)));w.append(d)})}
function setView(v){$("#canvasWrap").classList.toggle("hidden",v!=="editor"||!state.pages.length);$("#emptyState").classList.toggle("hidden",v!=="editor"||!!state.pages.length);$("#previewWrap").classList.toggle("hidden",v!=="preview")}
$("#prevPage").onclick=()=>{state.page=Math.max(0,state.page-1);render()};$("#nextPage").onclick=()=>{state.page=Math.min(state.pages.length-1,state.page+1);render()};
$("#newLayout").onclick=async()=>{if(!state.pages.length)return analyze(false);let b=$("#newLayout"),page=state.pages[state.page];b.disabled=true;b.textContent="구성 중…";try{if(state.apiKey){let prompt=`You are a manga page designer. Redesign only the layout for these ${page.length} panels on a 12x12 page. Respect reading direction ${state.readOrder}. Vary sizes and occasionally tilt one suitable emphasis/action panel between -7 and 7 degrees. Keep all panels inside line 13 and avoid harmful overlap. Return JSON only {"layouts":[{"x":1,"y":1,"w":6,"h":5,"rotation":0,"z":1}]}, in the same panel order. Panels: ${JSON.stringify(page.map(p=>({title:p.title,shot:p.shot,description:p.description})))}`;let data=await askGemini(prompt,.85),fallback=presetLayout(page.length,state.page);page.forEach((p,i)=>p.layout=normalizeLayout(data.layouts?.[i],fallback[i]));log(`Gemini가 Page ${state.page+1} 컷 구성을 다시 설계했습니다.`)}else{let count=page.length,max=(layoutSets[count]||layoutSets[8]).length;state.layouts[state.page]=((state.layouts[state.page]||0)+1)%max;let fallback=presetLayout(count,state.page,state.layouts[state.page]);page.forEach((p,i)=>p.layout=normalizeLayout({...fallback[i],rotation:i===state.layouts[state.page]%count?(state.layouts[state.page]%2?5:-5):0},fallback[i]));log("데모 엔진이 컷 구성을 변경했습니다.")}history(`Page ${state.page+1} 레이아웃 변경`);render()}catch(e){log(`${e.message}: 레이아웃을 유지합니다.`)}b.disabled=false;b.textContent="다른 레이아웃"};
async function queue(one){let a=one?[one]:state.pages.flat().filter(p=>p.status!=="generated");if(!a.length)return;state.queueStop=false;$("#queueBar").classList.remove("hidden");for(let i=0;i<a.length;i++){if(state.queueStop)break;$("#queueText").textContent=`패널 ${i+1} / ${a.length} 생성 중`;$("#queueProgress").style.width=`${i/a.length*100}%`;a[i].status="generating";render();await new Promise(r=>setTimeout(r,+$("#interval").value));if(!state.queueStop){a[i].status="generated";render()}}$("#queueProgress").style.width="100%";$("#queueText").textContent=state.queueStop?"생성 중지됨":"모든 패널 생성 완료";setTimeout(()=>$("#queueBar").classList.add("hidden"),1200);history("NAI Generate")}
$("#generateAll").onclick=()=>queue();$("#generatePanel").onclick=()=>queue(selected());$("#stopQueue").onclick=()=>state.queueStop=true;
function history(label){state.history.unshift({id:crypto.randomUUID(),label,date:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}),pages:structuredClone(state.pages),layouts:[...state.layouts]});state.history=state.history.slice(0,8);renderHistory()}
function renderHistory(){if(!state.history.length)return;let l=$("#historyList");l.innerHTML="";state.history.forEach(h=>{let d=document.createElement("div");d.className="history-item";d.innerHTML=`<span><b>${h.label}</b> · ${h.pages.flat().length} panels · ${h.date}</span><button>복원</button>`;$("button",d).onclick=()=>{state.pages=structuredClone(h.pages);state.layouts=[...(h.layouts||[])];state.page=0;render()};l.append(d)})}
$("#clearHistory").onclick=()=>{state.history=[];$("#historyList").innerHTML='<p class="help">레이아웃 이력이 비었습니다.</p>'};$("#summarize").onclick=()=>{let t=$("#mangaPrompt").value.trim();if(t)log(`요약: ${t.slice(0,110)}${t.length>110?"…":""}`)};
$("#downloadJson").onclick=()=>{let b=new Blob([JSON.stringify({version:1,title:$("#projectTitle").value,prompt:$("#mangaPrompt").value,characters:state.characters,pages:state.pages,layouts:state.layouts},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="toonit-manga.json";a.click();URL.revokeObjectURL(a.href)};
$("#uploadJson").onclick=()=>$("#jsonFile").click();$("#jsonFile").onchange=e=>{let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);state.pages=normalizePages({pages:d.pages||[]});state.layouts=d.layouts||state.pages.map((_,i)=>i%3);state.characters=d.characters||state.characters;$("#projectTitle").value=d.title||"Imported Manga";$("#mangaPrompt").value=d.prompt||"";state.page=0;renderCharacters();render();log("JSON 프로젝트를 불러왔습니다.")}catch{log("JSON 형식이 올바르지 않습니다.")}};r.readAsText(e.target.files[0])};
$("#newProject").onclick=()=>{if(confirm("현재 프로젝트를 비우고 새로 시작할까요?")){state.pages=[];state.layouts=[];state.selected=null;state.history=[];$("#projectTitle").value="새 만화";$("#mangaPrompt").value="";render()}};$("#openSettings").onclick=()=>{$("#apiKey").value=state.apiKey;$("#textModel").value=state.model;$("#apiTestResult").textContent="";$("#settingsDialog").showModal()};$("#saveSettings").onclick=()=>{state.apiKey=$("#apiKey").value.trim();state.model=$("#textModel").value.trim();sessionStorage.setItem("toonitKey",state.apiKey);localStorage.setItem("toonitModel",state.model);log(state.apiKey?"Gemini API 키를 저장했습니다.":"데모 엔진을 사용합니다.")};
$("#testApi").onclick=async()=>{let key=$("#apiKey").value.trim(),model=$("#textModel").value.trim(),out=$("#apiTestResult");if(!key){out.textContent="키를 입력하세요.";return}out.textContent="연결 확인 중…";try{let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}?key=${encodeURIComponent(key)}`);if(!r.ok)throw Error(`${r.status} ${r.statusText}`);out.textContent=`연결 성공 · ${key.slice(0,2)}… 접두사 사용 가능`}catch(e){out.textContent=`연결 실패 · ${e.message}`}};
load();count();renderCharacters();render();
