const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const defaults=[{id:crypto.randomUUID(),name:"모카",description:"anthropomorphic black cat detective, amber eyes, beige trench coat, dark fedora",negative:"",x:.5,y:.5},{id:crypto.randomUUID(),name:"루나",description:"small glowing moon spirit, silver hair, star-shaped pupils, floating white dress",negative:"",x:.5,y:.5}];
function storedJson(key,fallback){try{return{...fallback,...JSON.parse(localStorage.getItem(key))}}catch{return fallback}}
const state={pages:[],layouts:[],page:0,selected:null,characters:defaults,storyImages:[],readOrder:"rtl",history:[],queueStop:false,queueAbort:null,apiKey:sessionStorage.getItem("toonitKey")||"",naiApiKey:sessionStorage.getItem("toonitNaiKey")||"",model:localStorage.getItem("toonitModel")||"gemini-2.5-flash",imageProvider:localStorage.getItem("toonitImageProvider")||"simulation",naiModel:localStorage.getItem("toonitNaiModel")||"nai-diffusion-4-5-full",naiProxyUrl:localStorage.getItem("toonitNaiProxyUrl")||"",naiResolution:localStorage.getItem("toonitNaiResolution")||"832x1216",naiGeneration:storedJson("toonitNaiGeneration",{sampler:"k_euler_ancestral",schedule:"native",steps:28,scale:5,cfgRescale:.4,varPlus:false})};
const layoutSets={2:[[[1,1,13,7],[1,7,13,13]],[[1,1,8,13],[8,1,13,13]]],3:[[[1,1,13,7],[1,7,7,13],[7,7,13,13]],[[1,1,8,13],[8,1,13,6],[8,6,13,13]],[[1,1,7,6],[7,1,13,6],[1,6,13,13]]],4:[[[1,1,13,7],[1,7,6,13],[6,7,10,13],[10,7,13,13]],[[1,1,7,8],[7,1,13,5],[7,5,13,8],[1,8,13,13]],[[1,1,5,13],[5,1,13,6],[5,6,9,13],[9,6,13,13]]],5:[[[1,1,9,7],[9,1,13,7],[1,7,5,13],[5,7,9,13],[9,7,13,13]],[[1,1,7,5],[7,1,13,5],[1,5,9,10],[9,5,13,10],[1,10,13,13]]],6:[[[1,1,9,7],[9,1,13,4],[9,4,13,7],[1,7,5,13],[5,7,9,13],[9,7,13,13]],[[1,1,5,7],[5,1,9,7],[9,1,13,7],[1,7,7,10],[7,7,13,10],[1,10,13,13]]],7:[[[1,1,9,6],[9,1,13,4],[9,4,13,6],[1,6,5,10],[5,6,9,10],[9,6,13,10],[1,10,13,13]]],8:[[[1,1,7,5],[7,1,13,5],[1,5,5,9],[5,5,9,9],[9,5,13,9],[1,9,5,13],[5,9,9,13],[9,9,13,13]]]};
const beats=[["도시의 밤","와이드 샷","네온 불빛이 물웅덩이에 번지는 비 오는 밤거리. 모카가 우산을 쓰고 걷는다.","오늘도 별일 없는 하루군.","모카"],["수상한 편지","익스트림 클로즈업","모카가 초승달 봉인이 찍힌 은빛 편지를 발견한다.","이건 누구 편지지?","모카"],["달의 의뢰","미디엄 샷","편지를 펼치자 작은 달의 지도가 푸른 빛과 함께 공중에 떠오른다.","사라진 달을 찾아주세요.","모카,루나"],["탐정의 결심","로우 앵글","모카가 코트를 여미고 달이 사라진 밤하늘을 올려다본다.","좋아. 사건을 시작하지.","모카"],["옥상의 흔적","오버숄더 샷","젖은 옥상 난간 위에 반짝이는 달빛 가루가 이어져 있다.","흔적은 아직 따뜻해.","모카"],["그림자의 습격","더치 앵글","거대한 그림자가 옥상을 덮고 모카를 향해 손을 뻗는다.","쉽게 끝나진 않겠군!","모카"],["지하의 달","익스트림 와이드 샷","도시 아래 거대한 지하 호수에 달과 루나가 갇혀 있다.","드디어 찾았어.","모카,루나"],["달빛의 귀환","실루엣 와이드 샷","달이 도시 위로 돌아오고 모카와 루나가 옥상에 나란히 선다.","다음 사건도 부탁할게.","모카,루나"]];
const chunk=(a,n)=>Array.from({length:Math.ceil(a.length/n)},(_,i)=>a.slice(i*n,i*n+n));
function log(t){let d=document.createElement("div");d.className="log-msg";d.textContent=t;$("#messageLog").prepend(d)}
function saved(){clearTimeout(saved.t);$("#saveState").textContent="저장 중…";saved.t=setTimeout(()=>{$("#saveState").textContent="자동 저장됨";localStorage.setItem("toonitProject",JSON.stringify({pages:state.pages,layouts:state.layouts,characters:state.characters,title:$("#projectTitle").value,prompt:$("#mangaPrompt").value,base:$("#basePrompt").value,negative:$("#negativePrompt").value,readOrder:state.readOrder}))},350)}
function load(){try{let d=JSON.parse(localStorage.getItem("toonitProject"));if(!d)return;state.pages=normalizePages({pages:d.pages||[]});state.layouts=d.layouts||[];state.characters=d.characters||defaults;state.readOrder=d.readOrder||"rtl";$("#projectTitle").value=d.title||"새 프로젝트";$("#mangaPrompt").value=d.prompt||"";$("#basePrompt").value=d.base||$("#basePrompt").value;$("#negativePrompt").value=d.negative||$("#negativePrompt").value}catch{}}
function count(){$("#promptCount").textContent=`${$("#mangaPrompt").value.length}자`}
$$(".tabs button").forEach(b=>b.onclick=()=>{$$(".tabs button").forEach(x=>x.classList.toggle("active",x===b));$$(".tab-panel").forEach(x=>x.classList.remove("active"));$(`#${b.dataset.tab}Tab`).classList.add("active")});
$$(".view").forEach(b=>b.onclick=()=>{$$(".view").forEach(x=>x.classList.toggle("active",x===b));setView(b.dataset.view)});
["projectTitle","mangaPrompt","basePrompt","negativePrompt"].forEach(id=>$(`#${id}`).oninput=()=>{count();saved()});
$("#readOrder").onclick=e=>{if(!e.target.dataset.value)return;state.readOrder=e.target.dataset.value;$$("#readOrder button").forEach(b=>b.classList.toggle("active",b===e.target));render()};
$("#imageRatio").value=state.naiResolution;
$("#imageRatio").onchange=e=>{state.naiResolution=e.target.value;localStorage.setItem("toonitNaiResolution",state.naiResolution);state.pages.forEach(page=>page.forEach(p=>p.layout=normalizeLayout(p.layout,p.layout)));history("NAI 생성 비율 변경");render()};
const naiControlIds={naiSampler:"sampler",naiSchedule:"schedule",naiSteps:"steps",naiScale:"scale",naiCfgRescale:"cfgRescale",naiVarPlus:"varPlus"};
Object.entries(naiControlIds).forEach(([id,key])=>{let control=$(`#${id}`);control[control.type==="checkbox"?"checked":"value"]=state.naiGeneration[key];control.onchange=()=>{state.naiGeneration[key]=control.type==="checkbox"?control.checked:(control.type==="number"?Number(control.value):control.value);localStorage.setItem("toonitNaiGeneration",JSON.stringify(state.naiGeneration));saved()}});
function renderCharacters(){let l=$("#characterList");l.innerHTML="";state.characters.forEach(c=>{let n=$("#characterTemplate").content.cloneNode(true);$(".avatar",n).textContent=c.name[0]||"?";$(".char-name",n).value=c.name;$(".char-desc",n).value=c.description;$(".char-negative",n).value=c.negative||"";$(".char-x",n).value=c.x??.5;$(".char-y",n).value=c.y??.5;$(".char-name",n).oninput=e=>{c.name=e.target.value;saved()};$(".char-desc",n).oninput=e=>{c.description=e.target.value;saved()};$(".char-negative",n).oninput=e=>{c.negative=e.target.value;saved()};$(".char-x",n).oninput=e=>{c.x=Math.min(1,Math.max(0,+e.target.value||0));saved()};$(".char-y",n).oninput=e=>{c.y=Math.min(1,Math.max(0,+e.target.value||0));saved()};$(".remove-char",n).onclick=()=>{state.characters=state.characters.filter(x=>x.id!==c.id);renderCharacters();renderInspector()};l.append(n)})}
$("#addCharacter").onclick=()=>{state.characters.push({id:crypto.randomUUID(),name:`캐릭터 ${state.characters.length+1}`,description:"appearance, outfit, personality",negative:"",x:.5,y:.5});renderCharacters()};
function makePanel(b){let names=b[4].split(",").filter(n=>state.characters.some(c=>c.name===n));return{id:crypto.randomUUID(),title:b[0],shot:b[1],description:b[2],dialogue:b[3],characters:names,imagePrompt:`${$("#basePrompt").value}, ${b[1]}, ${b[2]}, no text`,negativePrompt:"",imageFit:"contain",vibes:[],vibeStrength:.6,vibeInformation:1,vibeNormalize:true,useImg2Img:false,img2imgStrength:.5,img2imgNoise:.05,preciseReferences:[],status:"ready",reference:""}}
const clamp=(n,min,max)=>{let value=Number(n);return Math.min(max,Math.max(min,Number.isFinite(value)?Math.round(value):min))};
const mangaPageRatio=1/1.414;
const naiShapes=[[832,1216],[896,1152],[960,1088],[1024,1024],[1088,960],[1152,896],[1216,832]].map(([width,height])=>({name:`${width}x${height}`,ratio:width/height,width,height}));
function selectedNaiShape(){return naiShapes.find(shape=>shape.name===state.naiResolution)||naiShapes[0]}
function presetLayout(count,pageIndex,variant=0){let set=layoutSets[count]||layoutSets[8],rects=set[variant%set.length];return rects.map((r,i)=>({x:r[0],y:r[1],w:r[2]-r[0],h:r[3]-r[1],rotation:(pageIndex+i)%5===3?(i%2?4:-4):0,z:i+1}))}
function normalizeLayout(layout,fallback={}){let x=clamp(layout?.x??fallback.x,1,11),y=clamp(layout?.y??fallback.y,1,11),w=clamp(layout?.w??fallback.w,2,13-x),h=clamp(layout?.h??fallback.h,2,13-y),shape=selectedNaiShape(),gridRatio=shape.ratio/mangaPageRatio,options=[];for(let candidateH=2;candidateH<=13-y;candidateH++){let candidateW=Math.round(candidateH*gridRatio);if(candidateW>=2&&candidateW<=13-x)options.push({w:candidateW,h:candidateH})}for(let candidateW=2;candidateW<=13-x;candidateW++){let candidateH=Math.round(candidateW/gridRatio);if(candidateH>=2&&candidateH<=13-y)options.push({w:candidateW,h:candidateH})}let best=options.reduce((a,b)=>Math.abs(b.w-w)+Math.abs(b.h-h)<Math.abs(a.w-w)+Math.abs(a.h-h)?b:a,{w,h});return{x,y,w:best.w,h:best.h,shape:shape.name,rotation:clamp(layout?.rotation??fallback.rotation??0,-7,7),z:clamp(layout?.z??fallback.z??1,1,20)}}
function normalizePages(raw){let source=Array.isArray(raw?.pages)?raw.pages:Array.isArray(raw?.panels)?chunk(raw.panels,Math.max(2,+$("#panelRange").value)):[];return source.map((page,pi)=>{let panels=Array.isArray(page)?page:page.panels||[],fallback=presetLayout(panels.length,pi);return panels.slice(0,8).map((x,i)=>({...x,id:x.id||crypto.randomUUID(),status:x.status||"ready",reference:x.reference||"",characters:Array.isArray(x.characters)?x.characters:[],negativePrompt:x.negativePrompt||"",imageFit:x.imageFit==="cover"?"cover":"contain",vibes:Array.isArray(x.vibes)?x.vibes.slice(0,5):[],vibeStrength:Number.isFinite(+x.vibeStrength)?+x.vibeStrength:.6,vibeInformation:Number.isFinite(+x.vibeInformation)?+x.vibeInformation:1,vibeNormalize:x.vibeNormalize!==false,useImg2Img:x.useImg2Img===true,img2imgStrength:Number.isFinite(+x.img2imgStrength)?+x.img2imgStrength:.5,img2imgNoise:Number.isFinite(+x.img2imgNoise)?+x.img2imgNoise:.05,preciseReferences:Array.isArray(x.preciseReferences)?x.preciseReferences.slice(0,5):[],imagePrompt:x.imagePrompt?.startsWith($("#basePrompt").value)?x.imagePrompt:`${$("#basePrompt").value}, ${x.imagePrompt||""}`,layout:normalizeLayout(x.layout,fallback[i])}))}).filter(x=>x.length)}
function demo(){let per=Math.max(2,+$("#panelRange").value),total=Math.max(1,+$("#pages").value)*per,pages=chunk(Array.from({length:total},(_,i)=>makePanel(beats[i%beats.length])),per);return pages.map((page,pi)=>{let fallback=presetLayout(page.length,pi);return page.map((p,i)=>({...p,layout:normalizeLayout(fallback[i],fallback[i])}))})}
async function askGemini(prompt,temperature,parts=[]){let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(state.model)}:generateContent?key=${encodeURIComponent(state.apiKey)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt},...parts]}],generationConfig:{responseMimeType:"application/json",temperature}})});if(!r.ok){let message=await r.text();throw Error(`Gemini ${r.status}: ${message.slice(0,300)}`)}let d=await r.json(),text=d.candidates?.[0]?.content?.parts?.map(x=>x.text||"").join("");if(!text)throw Error("Gemini가 스토리 데이터를 반환하지 않았습니다");return JSON.parse(text)}
async function gemini(deep){let pageCount=Math.max(1,+$("#pages").value),per=Math.max(2,+$("#panelRange").value),shape=selectedNaiShape(),gridRatio=(shape.ratio/mangaPageRatio).toFixed(3),prompt=`You are a professional manga director and page designer. Turn the story into exactly ${pageCount} pages with about ${per} panels per page (2-8 allowed when pacing benefits). Design the panel composition yourself; do not use a repetitive grid. Use a 12x12 grid on a portrait 1:1.414 page. Every panel will be generated by NovelAI at exactly ${shape.width}x${shape.height}; make each visible panel ratio match it, using grid w/h about ${gridRatio}. Layout x/y are start lines from 1 to 11, w/h keep the panel inside line 13, rotation is -7 to 7 degrees, and z is 1-20. Occasionally use a visibly tilted panel for action, shock, instability, or emphasis, but keep most panels straight and readable. Avoid harmful overlap; reserve breathing room and create varied panel sizes. Image prompts describe scene, action, lighting, and composition; do not repeat detailed character appearance because character captions are sent separately. ${deep?"Deep mode: prioritize visual continuity, dramatic page turns, bold composition, varied camera angles, and detailed prompts.":"Keep the storyboard concise and layouts readable."} Reading direction: ${state.readOrder}. Known characters: ${JSON.stringify(state.characters)}. Korean story: ${$("#mangaPrompt").value}. Return JSON only: {"pages":[{"panels":[{"title":"Korean","shot":"Korean camera","description":"Korean visual scene","dialogue":"Korean","characters":["known name"],"imagePrompt":"English scene prompt","negativePrompt":"English cut-specific negative prompt","layout":{"x":1,"y":1,"w":6,"h":6,"shape":"${shape.name}","rotation":0,"z":1}}]}]}`;let pages=normalizePages(await askGemini(prompt,deep?.9:.55));if(!pages.length)throw Error("Gemini가 유효한 페이지 구성을 반환하지 않았습니다");return pages}
async function analyze(deep){let b=deep?$("#geminiDeep"):$("#geminiLite");b.disabled=true;b.textContent="분석 중…";log(`${deep?"Deep":"Lite"} 분석을 시작했습니다.`);try{state.pages=state.apiKey?await gemini(deep):demo();log(`${state.apiKey?"Gemini":"데모 엔진"}가 ${state.pages.flat().length}개 컷을 구성했습니다.`)}catch(e){state.pages=demo();log(`${e.message}: 데모 구성으로 전환했습니다.`)}state.layouts=state.pages.map((_,i)=>i%3);state.page=0;state.selected=state.pages[0][0].id;history(deep?"Gemini Deep":"Gemini Lite");render();setView("editor");b.disabled=false;b.textContent=deep?"✦ Gemini Deep":"Gemini Lite"}
$("#geminiLite").onclick=()=>analyze(false);$("#geminiDeep").onclick=()=>analyze(true);
function imageData(dataUrl){let match=String(dataUrl).match(/^data:([^;]+);base64,(.+)$/);if(!match)throw Error("이미지 데이터를 읽을 수 없습니다");return{mimeType:match[1],data:match[2]}}
function resizeStoryImage(source){return new Promise((resolve,reject)=>{let image=new Image;image.onload=()=>{let scale=Math.min(1,1600/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.82))};image.onerror=reject;image.src=source})}
async function addStoryFiles(files){let room=12-state.storyImages.length,selected=[...files].filter(f=>f.type.startsWith("image/")).slice(0,room);for(const file of selected)state.storyImages.push(await resizeStoryImage(await blobDataUrl(file)));renderStoryImages()}
function renderStoryImages(){let list=$("#storyImageList");list.innerHTML="";if(!state.storyImages.length){list.innerHTML='<p class="help">최대 12개 이미지가 순서대로 Gemini에 전달됩니다.</p>';return}state.storyImages.forEach((image,i)=>{let d=document.createElement("div");d.className="story-image-item";d.style.backgroundImage=`url(${image})`;d.innerHTML=`<span>${i+1}</span><div><button data-move="-1">←</button><button data-move="1">→</button><button data-remove>×</button></div>`;$$("button[data-move]",d).forEach(button=>button.onclick=()=>{let target=i+Number(button.dataset.move);if(target<0||target>=state.storyImages.length)return;[state.storyImages[i],state.storyImages[target]]=[state.storyImages[target],state.storyImages[i]];renderStoryImages()});$("button[data-remove]",d).onclick=()=>{state.storyImages.splice(i,1);renderStoryImages()};list.append(d)})}
$("#storyImageFiles").onchange=e=>{addStoryFiles(e.target.files);e.target.value=""};
$("#usePanelImages").onclick=async()=>{let images=state.pages.flat().map(p=>p.reference).filter(Boolean).slice(0,12);state.storyImages=[];for(const image of images)state.storyImages.push(await resizeStoryImage(image));renderStoryImages();log(`${state.storyImages.length}개의 현재 컷 이미지를 가져왔습니다.`)};
$("#generateImageStory").onclick=async()=>{let button=$("#generateImageStory");if(!state.apiKey)return log("이미지 스토리 생성에는 Gemini API 키가 필요합니다.");if(!state.storyImages.length)return log("스토리 입력 이미지를 먼저 추가하세요.");let bytes=state.storyImages.reduce((sum,image)=>sum+imageData(image).data.length*.75,0);if(bytes>18_000_000)return log("이미지 입력이 너무 큽니다. 일부 이미지를 제거한 뒤 다시 시도하세요.");button.disabled=true;button.textContent="이미지 분석 중…";try{let shape=selectedNaiShape(),gridRatio=(shape.ratio/mangaPageRatio).toFixed(3),instruction=$("#imageStoryInstruction").value.trim()||"Create a coherent manga story following the images in their given order.",prompt=`You are a professional manga writer and storyboard director. Analyze the ${state.storyImages.length} ordered images supplied after this instruction. Build a coherent Korean-language manga story that follows their order. Preserve visible characters, actions, locations, and continuity; do not invent contradictions. User direction: ${instruction}. Group the images into pages with 2-8 panels each. Each panel must map to exactly one supplied image using imageIndex from 1 to ${state.storyImages.length}, and use every image exactly once. Use a portrait 12x12 grid. Target panel grid w/h ratio is about ${gridRatio}. Return JSON only: {"title":"Korean title","synopsis":"Korean complete story synopsis","characters":[{"name":"Korean name","description":"English visual appearance prompt","negative":"","x":0.5,"y":0.5}],"pages":[{"panels":[{"imageIndex":1,"title":"Korean scene title","shot":"Korean camera description","description":"Korean visual scene description","dialogue":"Korean dialogue or narration","characters":["character name"],"imagePrompt":"English prompt describing the visible image","negativePrompt":"","layout":{"x":1,"y":1,"w":6,"h":6,"rotation":0,"z":1}}]}]}`,parts=state.storyImages.map(image=>({inlineData:imageData(image)})),data=await askGemini(prompt,.65,parts);state.characters=Array.isArray(data.characters)&&data.characters.length?data.characters.slice(0,12).map(c=>({id:crypto.randomUUID(),name:c.name||"캐릭터",description:c.description||"",negative:c.negative||"",x:Number.isFinite(+c.x)?+c.x:.5,y:Number.isFinite(+c.y)?+c.y:.5})):state.characters;state.pages=normalizePages(data);state.pages.flat().forEach((panel,i)=>{let sourceIndex=Number(panel.imageIndex)-1;panel.reference=state.storyImages[sourceIndex>=0?sourceIndex:i]||"";panel.status=panel.reference?"generated":"ready"});if(!state.pages.length)throw Error("Gemini가 유효한 컷 구성을 반환하지 않았습니다");$("#projectTitle").value=data.title||"Image Story";$("#mangaPrompt").value=data.synopsis||instruction;state.layouts=state.pages.map((_,i)=>i%3);state.page=0;state.selected=state.pages[0][0].id;renderCharacters();count();history("Gemini 이미지 스토리");render();setView("editor");log(`${state.storyImages.length}개 이미지로 스토리와 컷 구성을 만들었습니다.`)}catch(e){log(`이미지 스토리 생성 실패: ${e.message}`)}button.disabled=false;button.textContent="✦ 이미지 스토리 생성"};
function layoutFor(count,pageIndex){let set=layoutSets[count]||layoutSets[8];return set[(state.layouts[pageIndex]||0)%set.length]}
function node(p,i,total,pageIndex){let n=$("#panelTemplate").content.cloneNode(true),a=$(".panel",n),image=$(".panel-image",n),rect=layoutFor(total,pageIndex)[i],fallback=rect&&{x:rect[0],y:rect[1],w:rect[2]-rect[0],h:rect[3]-rect[1],z:i+1},layout=p.layout||normalizeLayout(null,fallback);if(layout){a.style.gridColumn=`${layout.x} / span ${layout.w}`;a.style.gridRow=`${layout.y} / span ${layout.h}`;a.style.transform=`rotate(${layout.rotation||0}deg)`;a.style.zIndex=layout.z||i+1}a.classList.toggle("selected",p.id===state.selected);$(".panel-index",n).textContent=String(i+1).padStart(2,"0");$(".panel-name",n).textContent=p.title;$(".panel-camera",n).textContent=p.shot;$(".speech",n).textContent=p.dialogue;$(".panel-state",n).textContent=p.status.toUpperCase();if(p.status==="generated")image.classList.add("generated");image.classList.toggle("fit-cover",p.imageFit==="cover");if(p.reference){$(".panel-image-blur",n).style.backgroundImage=`url(${p.reference})`;$(".panel-image-main",n).style.backgroundImage=`url(${p.reference})`;$(".placeholder",n).style.display="none"}$(".panel-regenerate",n).onclick=e=>{e.stopPropagation();state.selected=p.id;queue(p)};a.ondragover=e=>{if([...e.dataTransfer.items].some(x=>x.kind==="file"&&x.type.startsWith("image/"))){e.preventDefault();a.classList.add("image-drop")}};a.ondragleave=()=>a.classList.remove("image-drop");a.ondrop=e=>{e.preventDefault();a.classList.remove("image-drop");let f=[...e.dataTransfer.files].find(x=>x.type.startsWith("image/"));if(f){state.selected=p.id;setPanelImage(p,f)}};a.onclick=()=>{state.selected=p.id;render()};return n}
function render(){let has=!!state.pages.length,page=state.pages[state.page]||[],c=$("#mangaPage");$("#emptyState").classList.toggle("hidden",has);$("#canvasWrap").classList.toggle("hidden",!has);$("#pageLabel").textContent=`Page ${has?state.page+1:0} / ${state.pages.length}`;c.innerHTML="";c.style.direction=state.readOrder;c.className=`manga-page count-${page.length}`;page.forEach((p,i)=>c.append(node(p,i,page.length,state.page)));renderInspector();renderPreview();renderHistory();saved()}
function selected(){return state.pages.flat().find(p=>p.id===state.selected)}
function renderVibes(p){let list=$("#panelVibeList");list.innerHTML="";(p.vibes||[]).forEach((v,i)=>{let d=document.createElement("div");d.className="vibe-item";d.style.backgroundImage=`url(${v})`;d.innerHTML="<button>×</button>";$("button",d).onclick=()=>{p.vibes.splice(i,1);renderVibes(p);saved()};list.append(d)})}
function renderPreciseReferences(p){let list=$("#panelPreciseList");list.innerHTML="";(p.preciseReferences||[]).forEach((reference,i)=>{let d=document.createElement("div");d.className="precise-item";d.innerHTML=`<i></i><span></span><button>×</button>`;$("i",d).style.backgroundImage=`url(${reference.image})`;$("span",d).textContent=`${reference.description||"설명 없음"} · ${reference.strength??.6} / ${reference.fidelity??.5}`;$("button",d).onclick=()=>{p.preciseReferences.splice(i,1);renderPreciseReferences(p);saved()};list.append(d)})}
function renderInspector(){let p=selected();$("#inspectorEmpty").classList.toggle("hidden",!!p);$("#inspector").classList.toggle("hidden",!p);if(!p)return;$("#panelBadge").textContent=`PANEL ${String(state.pages.flat().indexOf(p)+1).padStart(2,"0")}`;["Title","Shot","Description","Dialogue","ImagePrompt"].forEach(k=>$(`#panel${k}`).value=p[k[0].toLowerCase()+k.slice(1)]);$("#panelNegativePrompt").value=p.negativePrompt||"";$("#panelImageFit").value=p.imageFit==="cover"?"cover":"contain";$("#panelVibeStrength").value=p.vibeStrength??.6;$("#panelVibeInformation").value=p.vibeInformation??1;$("#panelVibeNormalize").checked=p.vibeNormalize!==false;$("#panelUseImg2Img").checked=p.useImg2Img===true;$("#panelImg2ImgStrength").value=p.img2imgStrength??.5;$("#panelImg2ImgNoise").value=p.img2imgNoise??.05;let x=$("#panelCharacters");x.innerHTML="";state.characters.forEach(c=>{let l=document.createElement("label");l.innerHTML=`<input type="checkbox" value="${c.id}" ${p.characters.includes(c.name)?"checked":""}> ${c.name}`;x.append(l)});renderVibes(p);renderPreciseReferences(p);let box=$(".reference-box");box.classList.toggle("has-image",!!p.reference);box.style.backgroundImage=p.reference?`url(${p.reference})`:"";$("#generatePanel").textContent=p.reference?"↻ 이 컷 이미지 재생성":"✦ 이 컷 이미지 생성"}
function syncPanelInspector(p){if(!p)return;["Title","Shot","Description","Dialogue","ImagePrompt"].forEach(k=>p[k[0].toLowerCase()+k.slice(1)]=$(`#panel${k}`).value);p.negativePrompt=$("#panelNegativePrompt").value;p.imageFit=$("#panelImageFit").value;p.vibeStrength=Math.min(1,Math.max(-1,+$("#panelVibeStrength").value||0));p.vibeInformation=Math.min(1,Math.max(0,+$("#panelVibeInformation").value||0));p.vibeNormalize=$("#panelVibeNormalize").checked;p.useImg2Img=$("#panelUseImg2Img").checked;p.img2imgStrength=Math.min(1,Math.max(0,+$("#panelImg2ImgStrength").value||0));p.img2imgNoise=Math.min(1,Math.max(0,+$("#panelImg2ImgNoise").value||0));p.characters=$$("#panelCharacters input:checked").map(x=>state.characters.find(c=>c.id===x.value)?.name).filter(Boolean)}
$("#savePanel").onclick=()=>{let p=selected();if(!p)return;syncPanelInspector(p);log(`「${p.title}」 컷을 수정했습니다.`);render()};
$("#panelVibeFiles").onchange=e=>{let p=selected(),files=[...e.target.files].slice(0,5-(p?.vibes?.length||0));if(!p||!files.length)return;p.vibes=p.vibes||[];Promise.all(files.map(f=>blobDataUrl(f))).then(images=>{p.vibes.push(...images);renderInspector();saved()});e.target.value=""};
$("#panelPreciseFiles").onchange=e=>{let p=selected(),files=[...e.target.files].slice(0,5-(p?.preciseReferences?.length||0));if(!p||!files.length)return;p.preciseReferences=p.preciseReferences||[];Promise.all(files.map(f=>blobDataUrl(f))).then(images=>{let description=$("#panelPreciseDescription").value.trim(),strength=Math.min(1,Math.max(0,+$("#panelPreciseStrength").value||0)),fidelity=Math.min(1,Math.max(0,+$("#panelPreciseFidelity").value||0)),information=Math.min(1,Math.max(0,+$("#panelPreciseInformation").value||0));p.preciseReferences.push(...images.map(image=>({image,description,strength,fidelity,information})));renderInspector();saved()});e.target.value=""};
$("#deletePanel").onclick=()=>{state.pages=state.pages.map(pg=>pg.filter(p=>p.id!==state.selected)).filter(pg=>pg.length);state.page=Math.max(0,Math.min(state.page,state.pages.length-1));state.selected=null;history("패널 삭제");render()};
function setPanelImage(p,f){if(!p||!f?.type.startsWith("image/"))return;let r=new FileReader();r.onload=()=>{p.reference=r.result;p.status="generated";history(`「${p.title}」 외부 이미지 적용`);render()};r.readAsDataURL(f)}
$("#referenceFile").onchange=e=>{setPanelImage(selected(),e.target.files[0]);e.target.value=""};
$(".reference-box").ondragover=e=>{if([...e.dataTransfer.items].some(x=>x.kind==="file"&&x.type.startsWith("image/"))){e.preventDefault();e.currentTarget.classList.add("image-drop")}};
$(".reference-box").ondragleave=e=>e.currentTarget.classList.remove("image-drop");
$(".reference-box").ondrop=e=>{e.preventDefault();e.currentTarget.classList.remove("image-drop");setPanelImage(selected(),[...e.dataTransfer.files].find(x=>x.type.startsWith("image/")))};
function renderPreview(){let w=$("#previewWrap");w.innerHTML="";state.pages.forEach((pg,pi)=>{let d=document.createElement("div");d.className="preview-page";d.style.direction=state.readOrder;pg.forEach((p,i)=>d.append(node(p,i,pg.length,pi)));w.append(d)})}
function setView(v){$("#canvasWrap").classList.toggle("hidden",v!=="editor"||!state.pages.length);$("#emptyState").classList.toggle("hidden",v!=="editor"||!!state.pages.length);$("#previewWrap").classList.toggle("hidden",v!=="preview")}
$("#prevPage").onclick=()=>{state.page=Math.max(0,state.page-1);render()};$("#nextPage").onclick=()=>{state.page=Math.min(state.pages.length-1,state.page+1);render()};
$("#newLayout").onclick=async()=>{if(!state.pages.length)return analyze(false);let b=$("#newLayout"),page=state.pages[state.page],shape=selectedNaiShape(),gridRatio=(shape.ratio/mangaPageRatio).toFixed(3);b.disabled=true;b.textContent="구성 중…";try{if(state.apiKey){let prompt=`You are a manga page designer. Redesign only the layout for these ${page.length} panels on a portrait 12x12 grid page. Respect reading direction ${state.readOrder}. Every panel will use NovelAI ${shape.width}x${shape.height}; make visible grid w/h about ${gridRatio}. Vary sizes and occasionally tilt one suitable emphasis/action panel between -7 and 7 degrees. Keep all panels inside line 13 and avoid harmful overlap. Return JSON only {"layouts":[{"x":1,"y":1,"w":6,"h":6,"shape":"${shape.name}","rotation":0,"z":1}]}, in the same panel order. Panels: ${JSON.stringify(page.map(p=>({title:p.title,shot:p.shot,description:p.description})))}`;let data=await askGemini(prompt,.85),fallback=presetLayout(page.length,state.page);page.forEach((p,i)=>p.layout=normalizeLayout(data.layouts?.[i],fallback[i]));log(`Gemini가 Page ${state.page+1} 컷 구성을 다시 설계했습니다.`)}else{let count=page.length,max=(layoutSets[count]||layoutSets[8]).length;state.layouts[state.page]=((state.layouts[state.page]||0)+1)%max;let fallback=presetLayout(count,state.page,state.layouts[state.page]);page.forEach((p,i)=>p.layout=normalizeLayout({...fallback[i],rotation:i===state.layouts[state.page]%count?(state.layouts[state.page]%2?5:-5):0},fallback[i]));log("데모 엔진이 컷 구성을 변경했습니다.")}history(`Page ${state.page+1} 레이아웃 변경`);render()}catch(e){log(`${e.message}: 레이아웃을 유지합니다.`)}b.disabled=false;b.textContent="다른 레이아웃"};
function panelImageSize(){let shape=selectedNaiShape();return{width:shape.width,height:shape.height}}
function blobDataUrl(blob){return new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}
function naiUrl(path){return`${state.naiProxyUrl.replace(/\/+$/,"")}${path}`}
async function apiJson(response){let type=response.headers.get("content-type")||"",text=await response.text();if(!type.includes("application/json"))throw Error(`NovelAI 프록시가 JSON 대신 ${type||"알 수 없는 응답"}을 반환했습니다. npm start로 서버를 실행하거나 NovelAI proxy URL을 설정하세요.`);let data;try{data=JSON.parse(text)}catch{throw Error("NovelAI 프록시가 올바르지 않은 JSON을 반환했습니다.")}if(!response.ok)throw Error(data.error||`NovelAI ${response.status}`);return data}
async function generateImage(panel){if(state.imageProvider==="simulation"){await new Promise(r=>setTimeout(r,+$("#interval").value));return panel.reference||""}let size=panelImageSize(panel),characters=state.characters.filter(c=>panel.characters.includes(c.name)).slice(0,5).map(c=>({prompt:c.description||c.name,negative:c.negative||"",x:c.x??.5,y:c.y??.5})),negativePrompt=[$("#negativePrompt").value,panel.negativePrompt].filter(Boolean).join(", "),r=await fetch(naiUrl("/api/nai/generate"),{method:"POST",headers:{"Content-Type":"application/json"},signal:state.queueAbort.signal,body:JSON.stringify({apiKey:state.naiApiKey,prompt:panel.imagePrompt,negativePrompt,characters,vibes:(panel.vibes||[]).slice(0,5),vibeStrength:panel.vibeStrength??.6,vibeInformation:panel.vibeInformation??1,vibeNormalize:panel.vibeNormalize!==false,initImage:panel.useImg2Img?panel.reference:"",img2imgStrength:panel.img2imgStrength??.5,img2imgNoise:panel.img2imgNoise??.05,preciseReferences:(panel.preciseReferences||[]).slice(0,5),model:state.naiModel,...state.naiGeneration,...size})});if(!r.ok){await apiJson(r)}if(!(r.headers.get("content-type")||"").includes("image/"))throw Error("NovelAI 프록시가 이미지 대신 다른 응답을 반환했습니다.");panel.seed=Number(r.headers.get("X-NAI-Seed"))||panel.seed;return blobDataUrl(await r.blob())}
async function queue(one){if(state.queueAbort)return log("이미지 생성 큐가 이미 실행 중입니다.");let a=one?[one]:state.pages.flat().filter(p=>p.status!=="generated");if(!a.length)return;state.queueStop=false;state.queueAbort=new AbortController;$("#queueBar").classList.remove("hidden");for(let i=0;i<a.length;i++){if(state.queueStop)break;$("#queueText").textContent=`패널 ${i+1} / ${a.length} 생성 중`;$("#queueProgress").style.width=`${i/a.length*100}%`;a[i].status="generating";render();try{let image=await generateImage(a[i]);if(state.queueStop)break;if(image)a[i].reference=image;a[i].status="generated"}catch(e){a[i].status="error";log(`${a[i].title}: ${e.message}`);if(e.name==="AbortError")break}render()}state.queueAbort=null;$("#queueProgress").style.width="100%";$("#queueText").textContent=state.queueStop?"생성 중지됨":"이미지 생성 완료";setTimeout(()=>$("#queueBar").classList.add("hidden"),1200);history(state.imageProvider==="novelai"?"NAI Generate":"Simulation Generate")}
$("#generateAll").onclick=()=>queue();$("#generatePanel").onclick=()=>{let p=selected();if(p){syncPanelInspector(p);queue(p)}};$("#stopQueue").onclick=()=>{state.queueStop=true;state.queueAbort?.abort()};
function history(label){state.history.unshift({id:crypto.randomUUID(),label,date:new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"}),pages:structuredClone(state.pages),layouts:[...state.layouts]});state.history=state.history.slice(0,8);renderHistory()}
function renderHistory(){if(!state.history.length)return;let l=$("#historyList");l.innerHTML="";state.history.forEach(h=>{let d=document.createElement("div");d.className="history-item";d.innerHTML=`<span><b>${h.label}</b> · ${h.pages.flat().length} panels · ${h.date}</span><button>복원</button>`;$("button",d).onclick=()=>{state.pages=structuredClone(h.pages);state.layouts=[...(h.layouts||[])];state.page=0;render()};l.append(d)})}
$("#clearHistory").onclick=()=>{state.history=[];$("#historyList").innerHTML='<p class="help">레이아웃 이력이 비었습니다.</p>'};$("#summarize").onclick=()=>{let t=$("#mangaPrompt").value.trim();if(t)log(`요약: ${t.slice(0,110)}${t.length>110?"…":""}`)};
$("#downloadJson").onclick=()=>{let b=new Blob([JSON.stringify({version:1,title:$("#projectTitle").value,prompt:$("#mangaPrompt").value,characters:state.characters,pages:state.pages,layouts:state.layouts},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="toonit-manga.json";a.click();URL.revokeObjectURL(a.href)};
$("#uploadJson").onclick=()=>$("#jsonFile").click();$("#jsonFile").onchange=e=>{let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);state.pages=normalizePages({pages:d.pages||[]});state.layouts=d.layouts||state.pages.map((_,i)=>i%3);state.characters=d.characters||state.characters;$("#projectTitle").value=d.title||"Imported Manga";$("#mangaPrompt").value=d.prompt||"";state.page=0;renderCharacters();render();log("JSON 프로젝트를 불러왔습니다.")}catch{log("JSON 형식이 올바르지 않습니다.")}};r.readAsText(e.target.files[0])};
$("#newProject").onclick=()=>{if(confirm("현재 프로젝트를 비우고 새로 시작할까요?")){state.pages=[];state.layouts=[];state.selected=null;state.history=[];$("#projectTitle").value="새 만화";$("#mangaPrompt").value="";render()}};$("#openSettings").onclick=()=>{$("#apiKey").value=state.apiKey;$("#naiApiKey").value=state.naiApiKey;$("#textModel").value=state.model;$("#imageProvider").value=state.imageProvider;$("#naiModel").value=state.naiModel;$("#naiProxyUrl").value=state.naiProxyUrl;$("#apiTestResult").textContent="";$("#settingsDialog").showModal()};$("#saveSettings").onclick=()=>{state.apiKey=$("#apiKey").value.trim();state.naiApiKey=$("#naiApiKey").value.trim();state.model=$("#textModel").value.trim();state.imageProvider=$("#imageProvider").value;state.naiModel=$("#naiModel").value.trim()||"nai-diffusion-4-5-full";state.naiProxyUrl=$("#naiProxyUrl").value.trim();sessionStorage.setItem("toonitKey",state.apiKey);sessionStorage.setItem("toonitNaiKey",state.naiApiKey);localStorage.setItem("toonitModel",state.model);localStorage.setItem("toonitImageProvider",state.imageProvider);localStorage.setItem("toonitNaiModel",state.naiModel);localStorage.setItem("toonitNaiProxyUrl",state.naiProxyUrl);log(state.imageProvider==="novelai"?"NovelAI 이미지 생성을 사용합니다.":"이미지 생성 시뮬레이션을 사용합니다.")};
$("#testApi").onclick=async()=>{let key=$("#apiKey").value.trim(),naiKey=$("#naiApiKey").value.trim(),model=$("#textModel").value.trim(),out=$("#apiTestResult"),results=[];state.naiProxyUrl=$("#naiProxyUrl").value.trim();out.textContent="연결 확인 중…";try{if(key){let r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}?key=${encodeURIComponent(key)}`);if(!r.ok)throw Error(`Gemini ${r.status}`);results.push("Gemini 연결 성공")}if($("#imageProvider").value==="novelai"){let r=await fetch(naiUrl("/api/nai/test"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey:naiKey})}),d=await apiJson(r);results.push(`NovelAI 연결 성공${d.tier!=null?` · tier ${d.tier}`:""}`)}out.textContent=results.length?results.join(" / "):"Simulation 모드"}catch(e){out.textContent=`연결 실패 · ${e.message}`}};
load();count();renderCharacters();render();
